{% set version = "0.1.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-filearray
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/filearray_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/filearray/filearray_{{ version }}.tar.gz
  sha256: 27ecdbf30a33e245224091d193ab600af67d67d10dc7deba19f2c2ba7102c219

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-bh
    - r-rcpp
    - r-digest
    - r-uuid
    - r-fastmap
  run:
    - r-base
    - r-bh
    - r-rcpp
    - r-digest
    - r-uuid
    - r-fastmap

test:
  commands:
    - $R -e "library('filearray')"           # [not win]
    - "\"%R%\" -e \"library('filearray')\""  # [win]

about:
  home: https://github.com/dipterix/filearray
  license: LGPL-3.0-only
  summary: |
    Stores large arrays in files to avoid occupying large memories. Implemented with super
    fast gigabyte-level multi-threaded reading/writing via 'OpenMP'. Supports multiple
    non-character data types (double, float, complex, integer, logical, and raw).
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - dipterix
    - conda-forge/r

# Package: filearray
# Type: Package
# Title: File-Backed Array for Out-of-Memory Computation
# Version: 0.1.5
# Language: en-US
# Encoding: UTF-8
# License: LGPL-3
# URL: https://dipterix.org/filearray/, https://github.com/dipterix/filearray
# BugReports: https://github.com/dipterix/filearray/issues
# Authors@R: c( person( "Zhengjia", "Wang", role = c("aut", "cre", "cph"), email = "dipterix.wang@gmail.com" ))
# Description: Stores large arrays in files to avoid occupying large memories. Implemented with super fast gigabyte-level multi-threaded reading/writing via 'OpenMP'. Supports multiple non-character data types (double, float, complex, integer, logical, and raw).
# Imports: digest, methods, Rcpp
# Suggests: rmarkdown, knitr, testthat (>= 3.0.0)
# RoxygenNote: 7.2.1
# LinkingTo: BH, Rcpp
# Config/testthat/edition: 3
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2022-10-15 14:13:41 UTC; dipterix
# Author: Zhengjia Wang [aut, cre, cph]
# Maintainer: Zhengjia Wang <dipterix.wang@gmail.com>
# Repository: CRAN
# Date/Publication: 2022-10-16 07:42:32 UTC
